CanaryShop/CanaryShop/Controllers/MuaHangController.cs
using CanaryShop.Models;
using Models.Frameworks;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CanaryShop.Controllers
{
    public class MuaHangController : Controller
    {
        private OnlineShopDbContext dbContext = new OnlineShopDbContext();

        //hien thi danh sach cac don dat hang
        // GET: MuaHang
        public ActionResult Index()
        {
            return View(dbContext);
        }

        #region Thong tin don hang
        // GET: MuaHang/Details/5
        public ActionResult Details(int id)
        {
            return View(dbContext.GIOHANGs.Find(id));
        }
        #endregion

        #region Create gio hang
        // GET: MuaHang/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MuaHang/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "OrderID")] GIOHANG model)
        {
            var CartList = (List<CartVM>)Session["Cart"];
            var OrdetailsList = new List<OrderDetail>();
            CartList.ForEach(m =>
            {
                var _Product = dbContext.SANPHAMQAs.Find(m.Sanpham.MaSP);
                OrdetailsList.Add(new OrderDetail
                {
                    MaSP = _Product.MaSP,
                    SoLuong = m.SoLuong
                });
            });
            model.TrangThai = false;
            // Thêm danh sách OrderDetails
            model.OrderDetails = OrdetailsList;

            // Thêm bảng Order
            dbContext.GIOHANGs.Add(model);
            dbContext.SaveChanges();
            Session["Cart"] = null;
            return RedirectToAction("CreateSuccess");
        }

        public ActionResult CreateSuccess()
        {
            return View();
        }

        #endregion


        // GET: MuaHang/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: MuaHang/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        #region Delete don hang

        // POST: MuaHang/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var _Order = dbContext.GIOHANGs.Find(id);
            _Order.OrderDetails.ToList().ForEach(m => dbContext.OrderDetails.Remove(m));
            dbContext.GIOHANGs.Remove(_Order);
            dbContext.SaveChanges();
            return new EmptyResult();
        }

        #endregion

        #region Gio hang
        public ActionResult ShowCart()
        {
            return View();
        }

        public ActionResult AddToCart(int id)
        {
            var _Product = dbContext.SANPHAMQAs.Find(id);
            var CartList = new List<CartVM>();
            if (Session["Cart"] != null)
            {
                CartList = (List<CartVM>)Session["Cart"];
                var OldCart = CartList.Find(m => m.Sanpham.MaSP == id);
                if (OldCart != null)
                {
                    var NewCart = new CartVM { Sanpham = _Product, SoLuong = OldCart.SoLuong + 1 };
                    CartList.Remove(OldCart);
                    CartList.Add(NewCart);
                }
                else
                {
                    CartList.Add(new CartVM { Sanpham = _Product, SoLuong = 1 });
                }
            }
            else
            {
                CartList.Add(new CartVM { Sanpham = _Product, SoLuong = 1 });
            }
            Session["Cart"] = CartList;
            return RedirectToAction("ShowCart");
        }

        public ActionResult RemoveCart(int id)
        {
            var CartList = (List<CartVM>)Session["Cart"];
            var _Cart = CartList.SingleOrDefault(m => m.Sanpham.MaSP == id);
            CartList.Remove(_Cart);
            Session["Cart"] = CartList;
            return new EmptyResult();
        }
        #endregion
    }
}

CanaryShop/CanaryShop/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using Models.Frameworks;
using PagedList;
using System.Data.Entity;

namespace CanaryShop.Controllers
{
    public class SanPhamController : Controller
    {
        private OnlineShopDbContext dbContext = new OnlineShopDbContext();
        //
        // GET: /Product/
        
        public ActionResult AoKhoacNu(int ?page)
        {
            var sanpham = from s in dbContext.SANPHAMQAs
                          orderby s.MaSP
                          select s;

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(sanpham.ToPagedList(pageNumber, pageSize));
        }


        //Danh sach san pham co trong du lieu
        public ActionResult List(int ?page)
        {
            var sanpham = from s in dbContext.SANPHAMQAs
                           orderby s.MaSP
                           select s;

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(sanpham.ToPagedList(pageNumber, pageSize));
        }

        //Hien thi danh sach san pham
        public ViewResult Index( )
        {
            return View(dbContext.LOAISANPHAMs);
        }

        public ActionResult SanPhamID(int id)
        {
            return View(dbContext.SANPHAMQAs.Where(m => m.IDLoaiSP == id));
        }

        public ActionResult ChiTietSanPham(int id)
        {
            return View(dbContext.SANPHAMQAs.Find(id));
        }

        #region Create
        [HttpPost, Authorize]
        public ActionResult TaoMoiSP()
        {
            ViewBag.IDLoaiSP = new SelectList(dbContext.LOAISANPHAMs, "IDLoaiSP", "Ten");
            return View();
            }
        [HttpPost]
        public ActionResult TaoMoiSP([Bind(Exclude="IDLoaiSP")] SANPHAMQA model)
        {
            if(ModelState.IsValid)
            {
                dbContext.SANPHAMQAs.Add(model);
                dbContext.SaveChanges();
                return RedirectToAction("ChiTiet", new { id = model.MaSP });
            }
            ViewBag.IDLoaiSP = new SelectList(dbContext.LOAISANPHAMs, "IDLoaiSP", "Ten", model.IDLoaiSP);
            return View(model);
        }
        #endregion

        #region Edit
        public ActionResult ChinhSua(int id)
        {
            var sanpham = dbContext.SANPHAMQAs.Find(id);
            ViewBag.IDLoaiSP = new SelectList(dbContext.LOAISANPHAMs, "IDLoaiSP", "Ten", sanpham.IDLoaiSP);
            return View(sanpham);
        }

        [HttpPost]
        public ActionResult ChinhSua(SANPHAMQA model)
        {
            if(ModelState.IsValid)
            {
                dbContext.Entry(model).State = EntityState.Modified;
                dbContext.SaveChanges();
                return RedirectToAction("ChiTiet", new { id = model.MaSP });
            }
            ViewBag.IDLoaiSP = new SelectList(dbContext.LOAISANPHAMs, "IDLoaiSP", "Ten", model.IDLoaiSP);
            return View(model);
        }
    
        #endregion

        #region Delete
        [HttpPost]
        public ActionResult Xoa(int id)
        {
            var sanpham = dbContext.SANPHAMQAs.Find(id);
            dbContext.SANPHAMQAs.Remove(sanpham);
            dbContext.SaveChanges();
            return new EmptyResult();
        }

        #endregion
    }
}

CanaryShop/CanaryShop/Views/MuaHang/Create.cshtml
@model Models.Frameworks.GIOHANG
@using CanaryShop.Models
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Session["Cart"] != null)
{
    var _CartSession = (List<CartVM>)Session["Cart"];
    var Total = _CartSession.Sum(m => m.Sanpham.GiaBan * m.SoLuong);
    <div class="row" style="margin-left:20px">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Danh mục sản phẩm
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                                <tr>
                                    <th>Sản Phẩm</th>
                                    <th>Đơn Giá</th>
                                    <th>Số Lượng</th>
                                    <th>Thành Tiền</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in _CartSession)
                                {
                                    var SubTotal = item.SoLuong * item.Sanpham.GiaBan;
                                    <tr>
                                        <td>@item.Sanpham.TenSP</td>
                                        <td>@string.Format("{0:0,0 VNĐ}", item.Sanpham.GiaBan).Replace(",", ".")</td>
                                        <td>@item.SoLuong</td>
                                        <td> @string.Format("{0:0,0 VNĐ}", SubTotal).Replace(",", ".")</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    
    <div style="border-top: solid 2px #0094ff; margin:10px; padding:10px; font-size:20px; font-weight:bold; margin-left:20px">
        Tổng Tiền :@string.Format("{0:0,0 VNĐ}", @Total).Replace(",", ".")
    </div>
}

<section class="main-content" style="margin-left:20px">
    <div class="row">
        <div class="span12">
            <h4 class="title"style="color:red"><span class="text"><strong></strong>Thông tin khách hàng</span></h4>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <fieldset>
                    @if (ViewBag.Message != null)
                    {
                        <div style="border:solid 1px green">
                            @ViewBag.Message
                        </div>
                    }
                    @Html.ValidationSummary(true)
                    <div class="control-group">
                        <label class="control-label">Tên khách hàng</label>
                        <div class="controls">
                            @Html.TextBoxFor(model => model.KhachHang, new { @type = "text", @placeholder = "Tên khách hàng", @class = "input-xlarge" })
                            @Html.ValidationMessageFor(model => model.KhachHang)
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Email</label>
                        <div class="controls">
                            @Html.TextBoxFor(model => model.Email, new { @type = "text", @placeholder = "Email", @class = "input-xlarge" })
                            @Html.ValidationMessageFor(model => model.Email)

                        </div>
                    </div>
                   <div class="control-group">
                        <label class="control-label">Số điện thoại</label>
                        <div class="controls">
                            @Html.TextBoxFor(model => model.SDT, new { @type = "text", @placeholder = "Số điện thoại", @class = "input-xlarge" })
                            @Html.ValidationMessageFor(model => model.SDT)

                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Địa chỉ</label>
                        <div class="controls">
                            @Html.TextBoxFor(model => model.DiaChi, new { @type = "text", @placeholder = "Địa chỉ", @class = "input-xlarge" })
                            @Html.ValidationMessageFor(model => model.DiaChi)

                        </div>
                    </div>
                    <div class="control-group">
                        <input tabindex="3" class="btn btn-inverse large" type="submit" value="Gửi đơn đặt hàng">
                    </div>
                </fieldset>
            }
        </div>
    </div>
</section>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CanaryShop/CanaryShop/Views/MuaHang/CreateSuccess.cshtml
@{
    ViewBag.Title = "CreateSuccess";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<pre style="font-family:Arial; font-size:16px; font-weight:bold;">
    Đơn hàng của khách hàng đã được ghi nhận. Chúng tôi sẽ kiểm tra các thông tin đơn hàng và liên hệ với khách nhanh nhất có thể.

</pre>

CanaryShop/CanaryShop/Views/MuaHang/Details.cshtml
@model Models.Frameworks.GIOHANG
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<fieldset>
    <legend>Thông tin khác hàng</legend>
    <table>
        <tr>
            <td>@Html.DisplayNameFor(model => model.KhachHang)</td>
            <td>@Html.DisplayFor(model => model.KhachHang)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.Email)</td>
            <td>@Html.DisplayFor(model => model.Email)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.SDT)</td>
            <td>@Html.DisplayFor(model => model.SDT)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.DiaChi)</td>
            <td>@Html.DisplayFor(model => model.DiaChi)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.TrangThai)</td>
            <td>@Html.DisplayFor(model => model.TrangThai)</td>
        </tr>
    </table>
</fieldset>

<fieldset>
    <legend>Chi Tiết Đơn Hàng</legend>
    <table>
        <thead>
            <tr>
                <th>Sản Phẩm</th>
                <th>Đơn Giá</th>
                <th>Số Lượng</th>
                <th>Thành Tiền</th>
            </tr>
        </thead>
        <tbody>
            @{
                var Total = Model.OrderDetails.Sum(m => m.Sanpham.GiaBan * m.SoLuong);
            }
            @foreach (var item in Model.OrderDetails)
            {
                var SubTotal = item.SoLuong * item.Sanpham.GiaBan;
                <tr>
                    <td>@item.Sanpham.TenSP</td>
                    <td>@string.Format("{0:0,0 VNĐ}", item.Sanpham.GiaBan).Replace(",", ".")</td>
                    <td>@item.SoLuong</td>
                    <td>@string.Format("{0:0,0 VNĐ}", SubTotal).Replace(",", ".")</td>
                </tr>
            }
        </tbody>
    </table>
    <div style="border-top: solid 2px #0094ff; margin: 10px; padding: 10px; font-size: 20px; font-weight: bold;">
        Tổng Tiền :@string.Format("{0:0,0 VNĐ}", @Total).Replace(",", ".")
    </div>
</fieldset>

CanaryShop/CanaryShop/Views/MuaHang/Index.cshtml
@model IEnumerable<Models.Frameworks.GIOHANG>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $(function () {
        $('.RemoveLink').click(function () {
            var x = $(this).attr("data-id");
            if (confirm("Đối tượng sẽ bị xóa.Bạn có muốn không ?")) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete", "Order")',
                    data: { id: x }
                });
                $("#row-" + x).remove();
            }
        })
    })
</script>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.KhachHang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SDT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DiaChi)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr id="row-@item.OrderID">
            <td>
                @Html.DisplayFor(modelItem => item.KhachHang)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SDT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.ActionLink("Chi tiết", "Details", new { id = item.OrderID }) |
                <a href="#" class="RemoveLink" data-id="@item.OrderID">Xóa</a>
            </td>
        </tr>
    }
</table>

CanaryShop/CanaryShop/Views/MuaHang/ShowCart.cshtml
@using CanaryShop.Models
@{
    ViewBag.Title = "ShowCart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $(function () {
        $('.RemoveLink').click(function () {
            var x = $(this).attr("data-id");
            if (confirm("Đối tượng sẽ bị xóa.Bạn có muốn không ?")) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("RemoveCart", "Shopping")',
                    data: { id: x }
                });
                $("#row-" + x).remove();
            }
        })
    })
</script>
@if (Session["Cart"] != null)
{
    var _CartSession = (List<CartVM>)Session["Cart"];
    var Total = _CartSession.Sum(m => m.Sanpham.GiaBan * m.SoLuong);
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading" style="text-align:center">
                    GIỎ HÀNG
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                                <tr>
                                    <th>Sản Phẩm</th>
                                    <th>Đơn Giá</th>
                                    <th>Số Lượng</th>
                                    <th>Thành Tiền</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in _CartSession)
                                {
                                    var SubTotal = item.SoLuong * item.Sanpham.GiaBan;
                                    <tr id="row-@item.Sanpham.MaSP">
                                        <td>@item.Sanpham.TenSP</td>
                                        <td>@string.Format("{0:0,0 VNĐ}", item.Sanpham.GiaBan).Replace(",", ".")</td>
                                        <td>@item.SoLuong</td>
                                        <td> @string.Format("{0:0,0 VNĐ}", SubTotal).Replace(",", ".")</td>
                                        <td><a style="color:blue" href="#" class="RemoveLink" data-id="@item.Sanpham.MaSP">Xóa</a></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div style="border-top: solid 2px #0094ff; margin:10px; padding:10px; font-size:20px; font-weight:bold;">
        Tổng Tiền: @string.Format("{0:0,0 VNĐ}", @Total).Replace(",", ".")
    </div>
    <p style="margin-left:20px">
        <a style="color:blue" href="@Url.Action("Create", "MuaHang") " class=" linkbutton1">
            Đặt Hàng |
        </a>
        <a style="color:blue" href="@Url.Action("Index", "SanPham")" class="linkButton1">
            Trở về Trang Chủ
        </a>
    </p>
}
else
{
    <h1>Giỏ hàng trống</h1>
    <p>
        <a style="color:blue" href="@Url.Action("Index","SanPham")" class="linkButton1">Trở về Trang Chủ</a>
    </p>

}